package recipe

import "errors"

// RetentionPolicy defines auto-eviction rules for episodes generated by this recipe.
// Adapted from openclaw/extensions/memory-core/retention.ts.
type RetentionPolicy struct {
	MaxAgeDays   int `json:"max_age_days,omitempty"`
	MaxPerScope  int `json:"max_per_scope,omitempty"`
	HalfLifeDays int `json:"half_life_days,omitempty"`
}

// Validate checks for reasonable retention limits.
func (p *RetentionPolicy) Validate() error {
	if p.MaxAgeDays < 0 {
		return errors.New("max_age_days cannot be negative")
	}
	if p.MaxPerScope < 0 {
		return errors.New("max_per_scope cannot be negative")
	}
	if p.HalfLifeDays < 0 {
		return errors.New("half_life_days cannot be negative")
	}
	return nil
}
